In [161]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import numpy as np

In [162]:
#полностью весь код готов для расстановки локализаций

f = open("./dataset_pose/poses/00.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))



(5.551115e-17, -4.440892e-16, 0)
(-0.04690294, 0.8586941, 1)
(-0.09374345, 1.716275, 2)
(-0.1406429, 2.574964, 3)
(-0.1874858, 3.432648, 4)
(-0.2343818, 4.291335, 5)
(-0.2812195, 5.148987, 6)
(-0.3281178, 6.007777, 7)
(-0.3749547, 6.865477, 8)
(-0.4218367, 7.724036, 9)
(-0.4687329, 8.582886, 10)
(-0.5155474, 9.440275, 11)
(-0.562431, 10.29896, 12)
(-0.6093087, 11.15757, 13)
(-0.6562052, 12.01541, 14)
(-0.7018788, 12.86965, 15)
(-0.7498241, 13.73146, 16)
(-0.7992511, 14.60026, 17)
(-0.8546642, 15.47957, 18)
(-0.9072868, 16.3694, 19)
20
x min = -0.907287, x_max = 0.000000, z_min = -0.000000, z_max = 16.369400


In [163]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1
    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1
    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1

elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1
    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:
    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1
    else:
        lst_lst_size = 2
    
print(lst_lst_size)

2


In [164]:
lst_lst = [[] for _ in range(lst_lst_size)]

print(len(lst_lst[0]))

lst = [xz_array[0]]
#lst_lst[0] = lst
#print(lst_lst[0][0])

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

        
        
        
xz_array_new = np.zeros((len(xz_array), 5))

class_number = -1

count = 0

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,0])
                xz_array_new[count] = sample
                
                count+=1

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:
                sample = np.append(item, [class_number,0])
                xz_array_new[count] = sample
                count+=1

                if xz_array_new[count][1] > 0 and xz_array_new[count][1]<1:
                    class_number+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,0])
                xz_array_new[count] = sample
                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,0])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,0])
                xz_array_new[count] = sample
                count+=1
                
                


0
0 [-0.8546642 15.47957   18.       ]
0 [-0.7992511 14.60026   17.       ]
0 [-0.7498241 13.73146   16.       ]
0 [-0.7018788 12.86965   15.       ]
0 [-0.6562052 12.01541   14.       ]
0 [-0.6093087 11.15757   13.       ]
0 [-0.562431 10.29896  12.      ]
0 [-0.5155474  9.440275  11.       ]
0 [-0.4687329  8.582886  10.       ]
0 [-0.4218367  7.724036   9.       ]
0 [-0.3749547  6.865477   8.       ]
0 [-0.3281178  6.007777   7.       ]
0 [-0.2812195  5.148987   6.       ]
0 [-0.2343818  4.291335   5.       ]
0 [-0.1874858  3.432648   4.       ]
0 [-0.1406429  2.574964   3.       ]
0 [-0.09374345  1.716275    2.        ]
0 [-0.04690294  0.8586941   1.        ]
[[-0.04690294  0.8586941   1.        ]
 [-0.09374345  1.716275    2.        ]
 [-0.1406429   2.574964    3.        ]
 [-0.1874858   3.432648    4.        ]
 [-0.2343818   4.291335    5.        ]
 [-0.2812195   5.148987    6.        ]
 [-0.3281178   6.007777    7.        ]
 [-0.3749547   6.865477    8.        ]
 [-0.4218367   7.

In [165]:
for x in xz_array:
    print(x)

[-0.9072868 16.3694    19.       ]
[-0.8546642 15.47957   18.       ]
[-0.7992511 14.60026   17.       ]
[-0.7498241 13.73146   16.       ]
[-0.7018788 12.86965   15.       ]
[-0.6562052 12.01541   14.       ]
[-0.6093087 11.15757   13.       ]
[-0.562431 10.29896  12.      ]
[-0.5155474  9.440275  11.       ]
[-0.4687329  8.582886  10.       ]
[-0.4218367  7.724036   9.       ]
[-0.3749547  6.865477   8.       ]
[-0.3281178  6.007777   7.       ]
[-0.2812195  5.148987   6.       ]
[-0.2343818  4.291335   5.       ]
[-0.1874858  3.432648   4.       ]
[-0.1406429  2.574964   3.       ]
[-0.09374345  1.716275    2.        ]
[-0.04690294  0.8586941   1.        ]
[ 5.551115e-17 -4.440892e-16  0.000000e+00]


In [166]:
for i in xz_array_new:
    print(i)

[-0.04690294  0.8586941   1.          0.          0.        ]
[-0.09374345  1.716275    2.          1.          0.        ]
[-0.1406429  2.574964   3.         2.         0.       ]
[-0.1874858  3.432648   4.         3.         0.       ]
[-0.2343818  4.291335   5.         4.         0.       ]
[-0.2812195  5.148987   6.         5.         0.       ]
[-0.3281178  6.007777   7.         6.         0.       ]
[-0.3749547  6.865477   8.         6.         0.       ]
[-0.4218367  7.724036   9.         7.         0.       ]
[-0.4687329  8.582886  10.         8.         0.       ]
[-0.5155474  9.440275  11.         9.         0.       ]
[-0.562431 10.29896  12.       10.        0.      ]
[-0.6093087 11.15757   13.        11.         0.       ]
[-0.6562052 12.01541   14.        12.         0.       ]
[-0.7018788 12.86965   15.        12.         0.       ]
[-0.7498241 13.73146   16.        13.         0.       ]
[-0.7992511 14.60026   17.        14.         0.       ]
[-0.8546642 15.47957   18.

In [167]:
end_class = xz_array_new[19][3]
print(end_class)

17.0


In [168]:
len(xz_array_new)

20

In [169]:
#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output00.npy', xz_array_new)

In [170]:


f = open("./dataset_pose/poses/01.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))


        

        



(1.110223e-16, -2.220446e-16, 0)
(0.05154656, 1.000725, 1)
(0.1464632, 1.995659, 2)
(0.2879204, 2.986691, 3)
(0.4657503, 3.963845, 4)
(0.6971645, 4.934639, 5)
(0.9715689, 5.887651, 6)
(1.288079, 6.826202, 7)
(1.651331, 7.743952, 8)
(2.050498, 8.64624, 9)
(2.488685, 9.527392, 10)
(2.966292, 10.38417, 11)
(3.483068, 11.2156, 12)
(4.03669, 12.01878, 13)
(4.631439, 12.79006, 14)
(5.252124, 13.53058, 15)
(5.913461, 14.23731, 16)
(6.602643, 14.91216, 17)
(7.315983, 15.55483, 18)
(8.059654, 16.155, 19)
20
x min = 0.000000, x_max = 8.059654, z_min = -0.000000, z_max = 16.155000


In [171]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1
    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1
    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1

elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1
    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:
    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1
    else:
        lst_lst_size = 2
    
print(lst_lst_size)

9


In [172]:
lst_lst = [[] for _ in range(lst_lst_size)]

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

0 [0.05154656 1.000725   1.        ]
0 [0.1464632 1.995659  2.       ]
0 [0.2879204 2.986691  3.       ]
0 [0.4657503 3.963845  4.       ]
0 [0.6971645 4.934639  5.       ]
0 [0.9715689 5.887651  6.       ]


In [173]:
lst_lst[0]

[array([ 1.110223e-16, -2.220446e-16,  0.000000e+00]),
 array([0.05154656, 1.000725  , 1.        ]),
 array([0.1464632, 1.995659 , 2.       ]),
 array([0.2879204, 2.986691 , 3.       ]),
 array([0.4657503, 3.963845 , 4.       ]),
 array([0.6971645, 4.934639 , 5.       ]),
 array([0.9715689, 5.887651 , 6.       ])]

In [174]:
xz_array_new = np.zeros((len(xz_array), 5))

class_number = end_class

count = 0

file_number = 1

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                
                count+=1

                if count==2:
                    print("count = 1 1 vetka %f" %(item[1]))

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:

                
                
                if count==1:
                    print("count = 1 2 vetka %f" %(item[1]))

                if (item[1] > 0 and xz_array_new[count][1]<1) or item[1] > 1:
                    class_number+=1
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                    
                else:
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                count+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1

[[ 1.110223e-16 -2.220446e-16  0.000000e+00]
 [ 5.154656e-02  1.000725e+00  1.000000e+00]
 [ 1.464632e-01  1.995659e+00  2.000000e+00]
 [ 2.879204e-01  2.986691e+00  3.000000e+00]
 [ 4.657503e-01  3.963845e+00  4.000000e+00]
 [ 6.971645e-01  4.934639e+00  5.000000e+00]
 [ 9.715689e-01  5.887651e+00  6.000000e+00]]
count = 1 2 vetka 1.000725
[[1.288079 6.826202 7.      ]
 [1.651331 7.743952 8.      ]]
[[ 2.050498  8.64624   9.      ]
 [ 2.488685  9.527392 10.      ]
 [ 2.966292 10.38417  11.      ]]
[[ 3.483068 11.2156   12.      ]]
[[ 4.03669  12.01878  13.      ]
 [ 4.631439 12.79006  14.      ]]
[[ 5.252124 13.53058  15.      ]
 [ 5.913461 14.23731  16.      ]]
[[ 6.602643 14.91216  17.      ]]
[[ 7.315983 15.55483  18.      ]]
[[ 8.059654 16.155    19.      ]]


In [175]:
print(len(xz_array))

20


In [176]:
print(len(xz_array_new))



#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output01.npy', xz_array_new)

for i in xz_array_new:
    print(i)
    
end_class = xz_array_new[19][3]
print(end_class)

20
[ 1.110223e-16 -2.220446e-16  0.000000e+00  1.800000e+01  1.000000e+00]
[ 0.05154656  1.000725    1.         19.          1.        ]
[ 0.1464632  1.995659   2.        19.         1.       ]
[ 0.2879204  2.986691   3.        20.         1.       ]
[ 0.4657503  3.963845   4.        21.         1.       ]
[ 0.6971645  4.934639   5.        22.         1.       ]
[ 0.9715689  5.887651   6.        23.         1.       ]
[ 1.288079  6.826202  7.       24.        1.      ]
[ 1.651331  7.743952  8.       25.        1.      ]
[ 2.050498  8.64624   9.       26.        1.      ]
[ 2.488685  9.527392 10.       27.        1.      ]
[ 2.966292 10.38417  11.       28.        1.      ]
[ 3.483068 11.2156   12.       29.        1.      ]
[ 4.03669 12.01878 13.      30.       1.     ]
[ 4.631439 12.79006  14.       30.        1.      ]
[ 5.252124 13.53058  15.       31.        1.      ]
[ 5.913461 14.23731  16.       32.        1.      ]
[ 6.602643 14.91216  17.       33.        1.      ]
[ 7.315983 

In [177]:
count = 0
for item in lst_lst:
    if len(item) !=0:
        count+=len(item)

print(count)

20


In [178]:
f = open("./dataset_pose/poses/02.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))



(1.110223e-16, -2.220446e-16, 0)
(0.005542524, 1.528975, 1)
(0.005664279, 3.052409, 2)
(0.003267206, 4.566315, 3)
(-0.006648871, 6.079413, 4)
(-0.01843176, 7.615299, 5)
(-0.03171614, 9.099118, 6)
(-0.04480997, 10.59934, 7)
(-0.06193958, 12.09423, 8)
(-0.08195167, 13.58737, 9)
(-0.1077803, 15.07594, 10)
(-0.1383473, 16.56039, 11)
(-0.1727573, 18.0428, 12)
(-0.2058484, 19.51642, 13)
(-0.2386867, 20.98968, 14)
(-0.2678747, 22.45164, 15)
(-0.2977989, 23.90871, 16)
(-0.3286901, 25.36099, 17)
(-0.3584, 26.80201, 18)
(-0.3881643, 28.23509, 19)
20
x min = -0.388164, x_max = 0.005664, z_min = -0.000000, z_max = 28.235090


In [179]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1
    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1
    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1

elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1
    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:
    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1
    else:
        lst_lst_size = 2
    
print(lst_lst_size)

2


In [180]:
lst_lst = [[] for _ in range(lst_lst_size)]

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

0 [-0.3584  26.80201 18.     ]
0 [-0.3286901 25.36099   17.       ]
0 [-0.2977989 23.90871   16.       ]
0 [-0.2678747 22.45164   15.       ]
0 [-0.2386867 20.98968   14.       ]
0 [-0.2058484 19.51642   13.       ]
0 [-0.1727573 18.0428    12.       ]
0 [-0.1383473 16.56039   11.       ]
0 [-0.1077803 15.07594   10.       ]
0 [-0.08195167 13.58737     9.        ]
0 [-0.06193958 12.09423     8.        ]
0 [-0.04480997 10.59934     7.        ]
0 [-0.03171614  9.099118    6.        ]
0 [-0.01843176  7.615299    5.        ]
0 [-0.00664887  6.079413    4.        ]
1 [3.267206e-03 4.566315e+00 3.000000e+00]
1 [0.00554252 1.528975   1.        ]
1 [0.00566428 3.052409   2.        ]


In [181]:
xz_array_new = np.zeros((len(xz_array), 5))

class_number = end_class

count = 0

file_number = 2

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                
                count+=1

                if count==2:
                    print("count = 1 1 vetka %f" %(item[1]))

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:

                
                
                if count==1:
                    print("count = 1 2 vetka %f" %(item[1]))

                if (item[1] > 0 and xz_array_new[count][1]<1) or item[1] > 1:
                    class_number+=1
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                    
                else:
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                count+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1

[[-6.648871e-03  6.079413e+00  4.000000e+00]
 [-1.843176e-02  7.615299e+00  5.000000e+00]
 [-3.171614e-02  9.099118e+00  6.000000e+00]
 [-4.480997e-02  1.059934e+01  7.000000e+00]
 [-6.193958e-02  1.209423e+01  8.000000e+00]
 [-8.195167e-02  1.358737e+01  9.000000e+00]
 [-1.077803e-01  1.507594e+01  1.000000e+01]
 [-1.383473e-01  1.656039e+01  1.100000e+01]
 [-1.727573e-01  1.804280e+01  1.200000e+01]
 [-2.058484e-01  1.951642e+01  1.300000e+01]
 [-2.386867e-01  2.098968e+01  1.400000e+01]
 [-2.678747e-01  2.245164e+01  1.500000e+01]
 [-2.977989e-01  2.390871e+01  1.600000e+01]
 [-3.286901e-01  2.536099e+01  1.700000e+01]
 [-3.584000e-01  2.680201e+01  1.800000e+01]
 [-3.881643e-01  2.823509e+01  1.900000e+01]]
[[ 1.110223e-16 -2.220446e-16  0.000000e+00]
 [ 5.542524e-03  1.528975e+00  1.000000e+00]
 [ 5.664279e-03  3.052409e+00  2.000000e+00]
 [ 3.267206e-03  4.566315e+00  3.000000e+00]]


In [182]:
print(len(xz_array_new))

#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output02.npy', xz_array_new)

for i in xz_array_new:
    print(i)


end_class = xz_array_new[19][3]
print(end_class)
                

20
[-6.648871e-03  6.079413e+00  4.000000e+00  3.600000e+01  2.000000e+00]
[-1.843176e-02  7.615299e+00  5.000000e+00  3.700000e+01  2.000000e+00]
[-3.171614e-02  9.099118e+00  6.000000e+00  3.800000e+01  2.000000e+00]
[-0.04480997 10.59934     7.         39.          2.        ]
[-0.06193958 12.09423     8.         40.          2.        ]
[-0.08195167 13.58737     9.         41.          2.        ]
[-0.1077803 15.07594   10.        42.         2.       ]
[-0.1383473 16.56039   11.        43.         2.       ]
[-0.1727573 18.0428    12.        44.         2.       ]
[-0.2058484 19.51642   13.        45.         2.       ]
[-0.2386867 20.98968   14.        46.         2.       ]
[-0.2678747 22.45164   15.        47.         2.       ]
[-0.2977989 23.90871   16.        48.         2.       ]
[-0.3286901 25.36099   17.        49.         2.       ]
[-0.3584  26.80201 18.      50.       2.     ]
[-0.3881643 28.23509   19.        51.         2.       ]
[ 1.110223e-16 -2.220446e-16  0.000

In [183]:
f = open("./dataset_pose/poses/03.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))



(-5.551115e-17, 2.220446e-16, 0)
(-0.01101102, 0.961713, 1)
(-0.01699529, 1.924885, 2)
(-0.03106702, 2.888054, 3)
(-0.04462738, 3.848312, 4)
(-0.05337242, 4.806551, 5)
(-0.06458549, 5.738958, 6)
(-0.07542792, 6.676395, 7)
(-0.08936429, 7.606157, 8)
(-0.1013034, 8.535486, 9)
(-0.1141317, 9.465868, 10)
(-0.1275574, 10.38892, 11)
(-0.1421945, 11.33952, 12)
(-0.1548813, 12.22345, 13)
(-0.1693123, 13.13325, 14)
(-0.1849063, 14.04136, 15)
(-0.1992846, 14.94552, 16)
(-0.2169483, 15.84627, 17)
(-0.236713, 16.74309, 18)
(-0.2548521, 17.63484, 19)
20
x min = -0.254852, x_max = -0.000000, z_min = 0.000000, z_max = 17.634840


In [184]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1

    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1

    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1


elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1

    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:

    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1

    else:
        lst_lst_size = 2

    
print(lst_lst_size)

here 5
1


In [185]:
lst_lst = [[] for _ in range(lst_lst_size)]

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if (idx+1)<len(xz_array):
                if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                    index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

0 [-0.236713 16.74309  18.      ]
0 [-0.2169483 15.84627   17.       ]
0 [-0.1992846 14.94552   16.       ]
0 [-0.1849063 14.04136   15.       ]
0 [-0.1693123 13.13325   14.       ]
0 [-0.1548813 12.22345   13.       ]
0 [-0.1421945 11.33952   12.       ]
0 [-0.1275574 10.38892   11.       ]
0 [-0.1141317  9.465868  10.       ]
0 [-0.1013034  8.535486   9.       ]
0 [-0.08936429  7.606157    8.        ]
0 [-0.07542792  6.676395    7.        ]
0 [-0.06458549  5.738958    6.        ]
0 [-0.05337242  4.806551    5.        ]
0 [-0.04462738  3.848312    4.        ]
0 [-0.03106702  2.888054    3.        ]
0 [-0.01699529  1.924885    2.        ]
0 [-0.01101102  0.961713    1.        ]
0 [-5.551115e-17  2.220446e-16  0.000000e+00]


In [186]:
xz_array_new = np.zeros((len(xz_array), 5))

class_number = end_class

count = 0

file_number = 3

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                
                count+=1

                if count==2:
                    print("count = 1 1 vetka %f" %(item[1]))

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:

                
                
                if count==1:
                    print("count = 1 2 vetka %f" %(item[1]))

                if (item[1] > 0 and xz_array_new[count][1]<1) or item[1] > 1:
                    class_number+=1
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                    
                else:
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                count+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1

[[-5.551115e-17  2.220446e-16  0.000000e+00]
 [-1.101102e-02  9.617130e-01  1.000000e+00]
 [-1.699529e-02  1.924885e+00  2.000000e+00]
 [-3.106702e-02  2.888054e+00  3.000000e+00]
 [-4.462738e-02  3.848312e+00  4.000000e+00]
 [-5.337242e-02  4.806551e+00  5.000000e+00]
 [-6.458549e-02  5.738958e+00  6.000000e+00]
 [-7.542792e-02  6.676395e+00  7.000000e+00]
 [-8.936429e-02  7.606157e+00  8.000000e+00]
 [-1.013034e-01  8.535486e+00  9.000000e+00]
 [-1.141317e-01  9.465868e+00  1.000000e+01]
 [-1.275574e-01  1.038892e+01  1.100000e+01]
 [-1.421945e-01  1.133952e+01  1.200000e+01]
 [-1.548813e-01  1.222345e+01  1.300000e+01]
 [-1.693123e-01  1.313325e+01  1.400000e+01]
 [-1.849063e-01  1.404136e+01  1.500000e+01]
 [-1.992846e-01  1.494552e+01  1.600000e+01]
 [-2.169483e-01  1.584627e+01  1.700000e+01]
 [-2.367130e-01  1.674309e+01  1.800000e+01]
 [-2.548521e-01  1.763484e+01  1.900000e+01]]


In [187]:
print(len(xz_array_new))

#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output03.npy', xz_array_new)

for i in xz_array_new:
    print(i)

end_class = xz_array_new[19][3]
print(end_class)

20
[-5.551115e-17  2.220446e-16  0.000000e+00  5.600000e+01  3.000000e+00]
[-1.101102e-02  9.617130e-01  1.000000e+00  5.600000e+01  3.000000e+00]
[-1.699529e-02  1.924885e+00  2.000000e+00  5.700000e+01  3.000000e+00]
[-3.106702e-02  2.888054e+00  3.000000e+00  5.800000e+01  3.000000e+00]
[-4.462738e-02  3.848312e+00  4.000000e+00  5.900000e+01  3.000000e+00]
[-5.337242e-02  4.806551e+00  5.000000e+00  6.000000e+01  3.000000e+00]
[-0.06458549  5.738958    6.         61.          3.        ]
[-0.07542792  6.676395    7.         62.          3.        ]
[-0.08936429  7.606157    8.         63.          3.        ]
[-0.1013034  8.535486   9.        64.         3.       ]
[-0.1141317  9.465868  10.        65.         3.       ]
[-0.1275574 10.38892   11.        66.         3.       ]
[-0.1421945 11.33952   12.        67.         3.       ]
[-0.1548813 12.22345   13.        68.         3.       ]
[-0.1693123 13.13325   14.        69.         3.       ]
[-0.1849063 14.04136   15.        70.

In [188]:
f = open("./dataset_pose/poses/04.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))



(-5.551115e-17, 2.220446e-16, 0)
(0.001289128, 1.310643, 1)
(0.0004448326, 2.625299, 2)
(0.002037581, 3.94173, 3)
(0.002777892, 5.261017, 4)
(0.004157928, 6.581638, 5)
(0.007571022, 7.908775, 6)
(0.008323818, 9.238962, 7)
(0.007728339, 10.56963, 8)
(0.006780918, 11.90426, 9)
(0.003419395, 13.24208, 10)
(-0.001862182, 14.58048, 11)
(-0.005851755, 15.93066, 12)
(-0.004267715, 17.28222, 13)
(0.000482789, 18.63469, 14)
(0.005006086, 19.9867, 15)
(0.004134686, 21.34127, 16)
(-0.0007654745, 22.70575, 17)
(-0.007369324, 24.0721, 18)
(-0.009719264, 25.44868, 19)
20
x min = -0.009719, x_max = 0.008324, z_min = 0.000000, z_max = 25.448680


In [189]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1
    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1
    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1

elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1
    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:
    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1
    else:
        lst_lst_size = 2
    
print(lst_lst_size)

2


In [190]:
lst_lst = [[] for _ in range(lst_lst_size)]

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

0 [-7.369324e-03  2.407210e+01  1.800000e+01]
0 [-5.851755e-03  1.593066e+01  1.200000e+01]
0 [-4.267715e-03  1.728222e+01  1.300000e+01]
0 [-1.862182e-03  1.458048e+01  1.100000e+01]
0 [-7.654745e-04  2.270575e+01  1.700000e+01]
0 [-5.551115e-17  2.220446e-16  0.000000e+00]
1 [4.827890e-04 1.863469e+01 1.400000e+01]
1 [1.289128e-03 1.310643e+00 1.000000e+00]
1 [2.037581e-03 3.941730e+00 3.000000e+00]
1 [2.777892e-03 5.261017e+00 4.000000e+00]
1 [3.419395e-03 1.324208e+01 1.000000e+01]
1 [4.134686e-03 2.134127e+01 1.600000e+01]
1 [4.157928e-03 6.581638e+00 5.000000e+00]
1 [5.006086e-03 1.998670e+01 1.500000e+01]
1 [6.780918e-03 1.190426e+01 9.000000e+00]
1 [7.571022e-03 7.908775e+00 6.000000e+00]
1 [7.728339e-03 1.056963e+01 8.000000e+00]
1 [8.323818e-03 9.238962e+00 7.000000e+00]


In [191]:
xz_array_new = np.zeros((len(xz_array), 5))

class_number = end_class

count = 0

file_number = 4

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                
                count+=1

                if count==2:
                    print("count = 1 1 vetka %f" %(item[1]))

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:

                
                
                if count==1:
                    print("count = 1 2 vetka %f" %(item[1]))

                if (item[1] > 0 and xz_array_new[count][1]<1) or item[1] > 1:
                    class_number+=1
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                    
                else:
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                count+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1

[[-5.551115e-17  2.220446e-16  0.000000e+00]
 [-1.862182e-03  1.458048e+01  1.100000e+01]
 [-5.851755e-03  1.593066e+01  1.200000e+01]
 [-4.267715e-03  1.728222e+01  1.300000e+01]
 [-7.654745e-04  2.270575e+01  1.700000e+01]
 [-7.369324e-03  2.407210e+01  1.800000e+01]
 [-9.719264e-03  2.544868e+01  1.900000e+01]]
[[1.289128e-03 1.310643e+00 1.000000e+00]
 [4.448326e-04 2.625299e+00 2.000000e+00]
 [2.037581e-03 3.941730e+00 3.000000e+00]
 [2.777892e-03 5.261017e+00 4.000000e+00]
 [4.157928e-03 6.581638e+00 5.000000e+00]
 [7.571022e-03 7.908775e+00 6.000000e+00]
 [8.323818e-03 9.238962e+00 7.000000e+00]
 [7.728339e-03 1.056963e+01 8.000000e+00]
 [6.780918e-03 1.190426e+01 9.000000e+00]
 [3.419395e-03 1.324208e+01 1.000000e+01]
 [4.827890e-04 1.863469e+01 1.400000e+01]
 [5.006086e-03 1.998670e+01 1.500000e+01]
 [4.134686e-03 2.134127e+01 1.600000e+01]]


In [192]:
print(len(xz_array_new))

#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output04.npy', xz_array_new)

for i in xz_array_new:
    print(i)
    
end_class = xz_array_new[19][3]
print(end_class)

20
[-5.551115e-17  2.220446e-16  0.000000e+00  7.400000e+01  4.000000e+00]
[-1.862182e-03  1.458048e+01  1.100000e+01  7.500000e+01  4.000000e+00]
[-5.851755e-03  1.593066e+01  1.200000e+01  7.600000e+01  4.000000e+00]
[-4.267715e-03  1.728222e+01  1.300000e+01  7.700000e+01  4.000000e+00]
[-7.654745e-04  2.270575e+01  1.700000e+01  7.800000e+01  4.000000e+00]
[-7.369324e-03  2.407210e+01  1.800000e+01  7.900000e+01  4.000000e+00]
[-9.719264e-03  2.544868e+01  1.900000e+01  8.000000e+01  4.000000e+00]
[1.289128e-03 1.310643e+00 1.000000e+00 8.100000e+01 4.000000e+00]
[4.448326e-04 2.625299e+00 2.000000e+00 8.200000e+01 4.000000e+00]
[2.037581e-03 3.941730e+00 3.000000e+00 8.300000e+01 4.000000e+00]
[2.777892e-03 5.261017e+00 4.000000e+00 8.400000e+01 4.000000e+00]
[4.157928e-03 6.581638e+00 5.000000e+00 8.500000e+01 4.000000e+00]
[7.571022e-03 7.908775e+00 6.000000e+00 8.600000e+01 4.000000e+00]
[8.323818e-03 9.238962e+00 7.000000e+00 8.700000e+01 4.000000e+00]
[7.728339e-03 1.056963e+

In [193]:
f = open("./dataset_pose/poses/05.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))



(1.110223e-16, 2.220446e-16, 0)
(0.003499723, 0.5653511, 1)
(0.001173954, 1.127607, 2)
(-0.007831705, 1.689225, 3)
(-0.01508128, 2.251296, 4)
(-0.02040073, 2.816072, 5)
(-0.02969353, 3.390281, 6)
(-0.04152744, 3.969489, 7)
(-0.05593704, 4.556204, 8)
(-0.07008098, 5.150463, 9)
(-0.08798198, 5.751285, 10)
(-0.1054713, 6.363942, 11)
(-0.1238576, 6.989627, 12)
(-0.1444743, 7.637602, 13)
(-0.1645124, 8.302111, 14)
(-0.1844755, 8.978383, 15)
(-0.2077191, 9.661917, 16)
(-0.2329992, 10.35368, 17)
(-0.253794, 11.06423, 18)
(-0.270128, 11.79839, 19)
20
x min = -0.270128, x_max = 0.003500, z_min = 0.000000, z_max = 11.798390


In [194]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1
    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1
    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1

elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1
    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:
    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1
    else:
        lst_lst_size = 2
    
print(lst_lst_size)

2


In [195]:
lst_lst = [[] for _ in range(lst_lst_size)]

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

0 [-0.253794 11.06423  18.      ]
0 [-0.2329992 10.35368   17.       ]
0 [-0.2077191  9.661917  16.       ]
0 [-0.1844755  8.978383  15.       ]
0 [-0.1645124  8.302111  14.       ]
0 [-0.1444743  7.637602  13.       ]
0 [-0.1238576  6.989627  12.       ]
0 [-0.1054713  6.363942  11.       ]
0 [-0.08798198  5.751285   10.        ]
0 [-0.07008098  5.150463    9.        ]
0 [-0.05593704  4.556204    8.        ]
0 [-0.04152744  3.969489    7.        ]
0 [-0.02969353  3.390281    6.        ]
0 [-0.02040073  2.816072    5.        ]
0 [-0.01508128  2.251296    4.        ]
0 [-0.0078317  1.689225   3.       ]
1 [1.173954e-03 1.127607e+00 2.000000e+00]
1 [0.00349972 0.5653511  1.        ]


In [196]:
xz_array_new = np.zeros((len(xz_array), 5))

class_number = end_class

count = 0

file_number = 5

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                
                count+=1

                if count==2:
                    print("count = 1 1 vetka %f" %(item[1]))

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:

                
                
                if count==1:
                    print("count = 1 2 vetka %f" %(item[1]))

                if (item[1] > 0 and xz_array_new[count][1]<1) or item[1] > 1:
                    class_number+=1
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                    
                else:
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                count+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1

[[-7.831705e-03  1.689225e+00  3.000000e+00]
 [-1.508128e-02  2.251296e+00  4.000000e+00]
 [-2.040073e-02  2.816072e+00  5.000000e+00]
 [-2.969353e-02  3.390281e+00  6.000000e+00]
 [-4.152744e-02  3.969489e+00  7.000000e+00]
 [-5.593704e-02  4.556204e+00  8.000000e+00]
 [-7.008098e-02  5.150463e+00  9.000000e+00]
 [-8.798198e-02  5.751285e+00  1.000000e+01]
 [-1.054713e-01  6.363942e+00  1.100000e+01]
 [-1.238576e-01  6.989627e+00  1.200000e+01]
 [-1.444743e-01  7.637602e+00  1.300000e+01]
 [-1.645124e-01  8.302111e+00  1.400000e+01]
 [-1.844755e-01  8.978383e+00  1.500000e+01]
 [-2.077191e-01  9.661917e+00  1.600000e+01]
 [-2.329992e-01  1.035368e+01  1.700000e+01]
 [-2.537940e-01  1.106423e+01  1.800000e+01]
 [-2.701280e-01  1.179839e+01  1.900000e+01]]
[[1.110223e-16 2.220446e-16 0.000000e+00]
 [3.499723e-03 5.653511e-01 1.000000e+00]
 [1.173954e-03 1.127607e+00 2.000000e+00]]


In [197]:
print(len(xz_array_new))

#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output05.npy', xz_array_new)

for i in xz_array_new:
    print(i)
    
end_class = xz_array_new[19][3]
print(end_class)

20
[-7.831705e-03  1.689225e+00  3.000000e+00  9.400000e+01  5.000000e+00]
[-1.508128e-02  2.251296e+00  4.000000e+00  9.500000e+01  5.000000e+00]
[-2.040073e-02  2.816072e+00  5.000000e+00  9.500000e+01  5.000000e+00]
[-2.969353e-02  3.390281e+00  6.000000e+00  9.600000e+01  5.000000e+00]
[-4.152744e-02  3.969489e+00  7.000000e+00  9.600000e+01  5.000000e+00]
[-5.593704e-02  4.556204e+00  8.000000e+00  9.700000e+01  5.000000e+00]
[-7.008098e-02  5.150463e+00  9.000000e+00  9.800000e+01  5.000000e+00]
[-8.798198e-02  5.751285e+00  1.000000e+01  9.800000e+01  5.000000e+00]
[-0.1054713  6.363942  11.        99.         5.       ]
[-0.1238576  6.989627  12.        99.         5.       ]
[ -0.1444743   7.637602   13.        100.          5.       ]
[ -0.1645124   8.302111   14.        101.          5.       ]
[ -0.1844755   8.978383   15.        101.          5.       ]
[ -0.2077191   9.661917   16.        102.          5.       ]
[ -0.2329992  10.35368    17.        103.          5.      

In [198]:
f = open("./dataset_pose/poses/06.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))



(0.0, 2.220446e-16, 0)
(-0.01401751, 1.198998, 1)
(-0.02787365, 2.384181, 2)
(-0.0418032, 3.575628, 3)
(-0.05573543, 4.767291, 4)
(-0.06970674, 5.962283, 5)
(-0.08362554, 7.152769, 6)
(-0.09756958, 8.3454, 7)
(-0.1114989, 9.536762, 8)
(-0.1254307, 10.72832, 9)
(-0.1393621, 11.91983, 10)
(-0.1533004, 13.11191, 11)
(-0.1671408, 14.30348, 12)
(-0.181814, 15.49659, 13)
(-0.1950729, 16.68758, 14)
(-0.2081761, 17.88104, 15)
(-0.2220687, 19.07663, 16)
(-0.2372951, 20.27019, 17)
(-0.2531559, 21.46468, 18)
(-0.2707637, 22.65883, 19)
20
x min = -0.270764, x_max = 0.000000, z_min = 0.000000, z_max = 22.658830


In [199]:
for i in xz_array:
    print(i)

[-0.2707637 22.65883   19.       ]
[-0.2531559 21.46468   18.       ]
[-0.2372951 20.27019   17.       ]
[-0.2220687 19.07663   16.       ]
[-0.2081761 17.88104   15.       ]
[-0.1950729 16.68758   14.       ]
[-0.181814 15.49659  13.      ]
[-0.1671408 14.30348   12.       ]
[-0.1533004 13.11191   11.       ]
[-0.1393621 11.91983   10.       ]
[-0.1254307 10.72832    9.       ]
[-0.1114989  9.536762   8.       ]
[-0.09756958  8.3454      7.        ]
[-0.08362554  7.152769    6.        ]
[-0.06970674  5.962283    5.        ]
[-0.05573543  4.767291    4.        ]
[-0.0418032  3.575628   3.       ]
[-0.02787365  2.384181    2.        ]
[-0.01401751  1.198998    1.        ]
[0.000000e+00 2.220446e-16 0.000000e+00]


In [200]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1
    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1
    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1

elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1
    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:
    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1
    else:
        lst_lst_size = 2
    
print(lst_lst_size)

2


In [201]:
lst_lst = [[] for _ in range(lst_lst_size)]

index = 0
for idx, i in enumerate(xz_array):
    
    
    if len(lst_lst[index])==0:

        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)

            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>=0:

                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

0 [-0.2531559 21.46468   18.       ]
0 [-0.2372951 20.27019   17.       ]
0 [-0.2220687 19.07663   16.       ]
0 [-0.2081761 17.88104   15.       ]
0 [-0.1950729 16.68758   14.       ]
0 [-0.181814 15.49659  13.      ]
0 [-0.1671408 14.30348   12.       ]
0 [-0.1533004 13.11191   11.       ]
0 [-0.1393621 11.91983   10.       ]
0 [-0.1254307 10.72832    9.       ]
0 [-0.1114989  9.536762   8.       ]
0 [-0.09756958  8.3454      7.        ]
0 [-0.08362554  7.152769    6.        ]
0 [-0.06970674  5.962283    5.        ]
0 [-0.05573543  4.767291    4.        ]
0 [-0.0418032  3.575628   3.       ]
0 [-0.02787365  2.384181    2.        ]
0 [-0.01401751  1.198998    1.        ]


In [202]:
print(len(lst_lst[1]))

1


In [203]:
xz_array_new = np.zeros((len(xz_array), 5))

class_number = end_class

count = 0

file_number = 6

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):

            
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                
                count+=1

                if count==2:
                    print("count = 1 1 vetka %f" %(item[1]))

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:

                
                if count==1:
                    print("count = 1 2 vetka %f" %(item[1]))

                if (item[1] > 0 and xz_array_new[count][1]<1) or item[1] > 1:
                    class_number+=1
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                    
                else:
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                count+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample

                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
                


[[-1.401751e-02  1.198998e+00  1.000000e+00]
 [-2.787365e-02  2.384181e+00  2.000000e+00]
 [-4.180320e-02  3.575628e+00  3.000000e+00]
 [-5.573543e-02  4.767291e+00  4.000000e+00]
 [-6.970674e-02  5.962283e+00  5.000000e+00]
 [-8.362554e-02  7.152769e+00  6.000000e+00]
 [-9.756958e-02  8.345400e+00  7.000000e+00]
 [-1.114989e-01  9.536762e+00  8.000000e+00]
 [-1.254307e-01  1.072832e+01  9.000000e+00]
 [-1.393621e-01  1.191983e+01  1.000000e+01]
 [-1.533004e-01  1.311191e+01  1.100000e+01]
 [-1.671408e-01  1.430348e+01  1.200000e+01]
 [-1.818140e-01  1.549659e+01  1.300000e+01]
 [-1.950729e-01  1.668758e+01  1.400000e+01]
 [-2.081761e-01  1.788104e+01  1.500000e+01]
 [-2.220687e-01  1.907663e+01  1.600000e+01]
 [-2.372951e-01  2.027019e+01  1.700000e+01]
 [-2.531559e-01  2.146468e+01  1.800000e+01]
 [-2.707637e-01  2.265883e+01  1.900000e+01]]
[[0.000000e+00 2.220446e-16 0.000000e+00]]


In [204]:
print(len(xz_array_new))

#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output06.npy', xz_array_new)

for i in xz_array_new:
    print(i)
    
end_class = xz_array_new[19][3]
print(end_class)

20
[-1.401751e-02  1.198998e+00  1.000000e+00  1.070000e+02  6.000000e+00]
[-2.787365e-02  2.384181e+00  2.000000e+00  1.080000e+02  6.000000e+00]
[-4.180320e-02  3.575628e+00  3.000000e+00  1.090000e+02  6.000000e+00]
[-5.573543e-02  4.767291e+00  4.000000e+00  1.100000e+02  6.000000e+00]
[-6.970674e-02  5.962283e+00  5.000000e+00  1.110000e+02  6.000000e+00]
[-8.362554e-02  7.152769e+00  6.000000e+00  1.120000e+02  6.000000e+00]
[-9.756958e-02  8.345400e+00  7.000000e+00  1.130000e+02  6.000000e+00]
[-1.114989e-01  9.536762e+00  8.000000e+00  1.140000e+02  6.000000e+00]
[ -0.1254307  10.72832     9.        115.          6.       ]
[ -0.1393621  11.91983    10.        116.          6.       ]
[ -0.1533004  13.11191    11.        117.          6.       ]
[ -0.1671408  14.30348    12.        118.          6.       ]
[ -0.181814  15.49659   13.       119.         6.      ]
[ -0.1950729  16.68758    14.        120.          6.       ]
[ -0.2081761  17.88104    15.        121.          6. 

In [205]:
f = open("./dataset_pose/poses/07.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))



(5.551115e-17, 2.220446e-16, 0)
(-0.004596714, 0.09154274, 1)
(-0.01001116, 0.1857373, 2)
(-0.01753371, 0.2834672, 3)
(-0.02863192, 0.38731, 4)
(-0.04273697, 0.5011396, 5)
(-0.06000009, 0.6279359, 6)
(-0.08275693, 0.7669396, 7)
(-0.1090497, 0.9191805, 8)
(-0.1415335, 1.081913, 9)
(-0.1816057, 1.251378, 10)
(-0.2325643, 1.425643, 11)
(-0.293459, 1.60414, 12)
(-0.3616512, 1.78864, 13)
(-0.4366243, 1.979231, 14)
(-0.5224919, 2.17302, 15)
(-0.620094, 2.368741, 16)
(-0.7248452, 2.565689, 17)
(-0.8394934, 2.758285, 18)
(-0.9687591, 2.950416, 19)
20
x min = -0.968759, x_max = 0.000000, z_min = 0.000000, z_max = 2.950416


In [206]:
lst_lst_size = 0
if np.min(x_array) < 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array)))+1 + int(np.max(x_array))+1
    
elif np.min(x_array) < 0 and np.max(x_array)<0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.min(x_array))) - int(np.max(x_array))  +1
    
elif np.min(x_array) >= 0 and np.max(x_array)>=0 and (int(np.min(x_array))!=int(np.max(x_array))):
    lst_lst_size = abs(int(np.max(x_array))) - int(np.min(x_array))  +1

elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))!=0 and int(np.max(x_array))!=0:
    lst_lst_size = 1
    
elif int(np.min(x_array))==int(np.max(x_array)) and int(np.min(x_array))==0 and int(np.max(x_array))==0:
    if (np.min(x_array)<0 and np.max(x_array)<0) or (np.min(x_array)>0 and np.max(x_array)>0):
        lst_lst_size = 1
    else:
        lst_lst_size = 2
    
print(lst_lst_size)

2


In [207]:
lst_lst = [[] for _ in range(lst_lst_size)]

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

0 [-0.8394934  2.758285  18.       ]
0 [-0.7248452  2.565689  17.       ]
0 [-0.620094  2.368741 16.      ]
0 [-0.5224919  2.17302   15.       ]
0 [-0.4366243  1.979231  14.       ]
0 [-0.3616512  1.78864   13.       ]
0 [-0.293459  1.60414  12.      ]
0 [-0.2325643  1.425643  11.       ]
0 [-0.1816057  1.251378  10.       ]
0 [-0.1415335  1.081913   9.       ]
0 [-0.1090497  0.9191805  8.       ]
0 [-0.08275693  0.7669396   7.        ]
0 [-0.06000009  0.6279359   6.        ]
0 [-0.04273697  0.5011396   5.        ]
0 [-0.02863192  0.38731     4.        ]
0 [-0.01753371  0.2834672   3.        ]
0 [-0.01001116  0.1857373   2.        ]
0 [-0.00459671  0.09154274  1.        ]


In [208]:
xz_array_new = np.zeros((len(xz_array), 5))

class_number = end_class

count = 0

file_number = 7

for i in lst_lst:
    if len(i)!=0:
        arr_sample = np.array(i)
        Y = arr_sample[arr_sample[:, 1].argsort()]
        print(Y)
        
        for idx, item in enumerate(Y):
            if idx == 0:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                
                count+=1

                if count==2:
                    print("count = 1 1 vetka %f" %(item[1]))

                
            #elif int(xz_array_new[count-1][1]) == 0:
            elif xz_array_new[count-1][1] > (-1) and xz_array_new[count-1][1]<0:

                
                
                if count==1:
                    print("count = 1 2 vetka %f" %(item[1]))

                if (item[1] > 0 and xz_array_new[count][1]<1) or item[1] > 1:
                    class_number+=1
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                    
                else:
                    sample = np.append(item, [class_number,file_number])
                    xz_array_new[count] = sample
                    
                count+=1

            elif int(xz_array_new[count-1][1]) < 1 and int(xz_array_new[count-1][1])>0:
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
                    
            elif int(xz_array_new[count-1][1]) == int(item[1]):
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1
            else:
                class_number+=1
                sample = np.append(item, [class_number,file_number])
                xz_array_new[count] = sample
                count+=1

[[-4.596714e-03  9.154274e-02  1.000000e+00]
 [-1.001116e-02  1.857373e-01  2.000000e+00]
 [-1.753371e-02  2.834672e-01  3.000000e+00]
 [-2.863192e-02  3.873100e-01  4.000000e+00]
 [-4.273697e-02  5.011396e-01  5.000000e+00]
 [-6.000009e-02  6.279359e-01  6.000000e+00]
 [-8.275693e-02  7.669396e-01  7.000000e+00]
 [-1.090497e-01  9.191805e-01  8.000000e+00]
 [-1.415335e-01  1.081913e+00  9.000000e+00]
 [-1.816057e-01  1.251378e+00  1.000000e+01]
 [-2.325643e-01  1.425643e+00  1.100000e+01]
 [-2.934590e-01  1.604140e+00  1.200000e+01]
 [-3.616512e-01  1.788640e+00  1.300000e+01]
 [-4.366243e-01  1.979231e+00  1.400000e+01]
 [-5.224919e-01  2.173020e+00  1.500000e+01]
 [-6.200940e-01  2.368741e+00  1.600000e+01]
 [-7.248452e-01  2.565689e+00  1.700000e+01]
 [-8.394934e-01  2.758285e+00  1.800000e+01]
 [-9.687591e-01  2.950416e+00  1.900000e+01]]
[[5.551115e-17 2.220446e-16 0.000000e+00]]


In [209]:
print(len(xz_array_new))

#сохраняем массив. [x, z, номер скана, номер локализации, номер папки]
np.save('output07.npy', xz_array_new)



for i in xz_array_new:
    print(i)

20
[-4.596714e-03  9.154274e-02  1.000000e+00  1.270000e+02  7.000000e+00]
[-1.001116e-02  1.857373e-01  2.000000e+00  1.270000e+02  7.000000e+00]
[-1.753371e-02  2.834672e-01  3.000000e+00  1.270000e+02  7.000000e+00]
[-2.863192e-02  3.873100e-01  4.000000e+00  1.270000e+02  7.000000e+00]
[-4.273697e-02  5.011396e-01  5.000000e+00  1.270000e+02  7.000000e+00]
[-6.000009e-02  6.279359e-01  6.000000e+00  1.270000e+02  7.000000e+00]
[-8.275693e-02  7.669396e-01  7.000000e+00  1.270000e+02  7.000000e+00]
[-1.090497e-01  9.191805e-01  8.000000e+00  1.270000e+02  7.000000e+00]
[ -0.1415335   1.081913    9.        128.          7.       ]
[ -0.1816057   1.251378   10.        128.          7.       ]
[ -0.2325643   1.425643   11.        128.          7.       ]
[ -0.293459   1.60414   12.       128.         7.      ]
[ -0.3616512   1.78864    13.        128.          7.       ]
[ -0.4366243   1.979231   14.        128.          7.       ]
[ -0.5224919   2.17302    15.        129.          7. 

In [213]:
array0 = np.load('output00.npy')
array1 = np.load('output01.npy')
array2 = np.load('output02.npy')
array3 = np.load('output03.npy')
array4 = np.load('output04.npy')
array5 = np.load('output05.npy')
array6 = np.load('output06.npy')
array7 = np.load('output07.npy')

array_shared = np.append(array0, array1, axis=0)
array_shared = np.append(array_shared, array2, axis=0)
array_shared = np.append(array_shared, array3, axis=0)
array_shared = np.append(array_shared, array4, axis=0)
array_shared = np.append(array_shared, array5, axis=0)
array_shared = np.append(array_shared, array6, axis=0)
array_shared = np.append(array_shared, array7, axis=0)
np.save('output_shared.npy', array_shared)

In [31]:
f = open("./dataset_pose/poses/08.txt", "r")

x_array = []
z_array = []

xz_array = []

for index, x in enumerate(f):
    x = x.split()
    value_x = x[3].replace(',', '.')
    x_array.append(float(value_x))
    value_z = x[11].replace(',', '.')
    z_array.append(float(value_z))
    
    xz_array.append((float(value_x), float(value_z), index))
    print(xz_array[index])
    
xz_array = np.array(xz_array)

xz_array = xz_array[xz_array[:, 0].argsort()]

print(len(xz_array))
print('x min = %f, x_max = %f, z_min = %f, z_max = %f' %(np.min(x_array), np.max(x_array), np.min(z_array), np.max(z_array)))

lst_lst = [[] for _ in range(809)]

index = 0
for idx, i in enumerate(xz_array):
    if len(lst_lst[index])==0:
        lst_lst[index].append(i)
        
    elif int(i[0]) == 0:
        if i[0] > (-1) and i[0]<0:
            print(index, i)
            lst_lst[index].append(i)
            if xz_array[idx+1][0] < 1 and xz_array[idx+1][0]>0:
                index+=1
                
        elif i[0] < 1 and i[0]>0:
            print(index, i)
            lst_lst[index].append(i)
                
            
    elif int(lst_lst[index][0][0]) == int(i[0]):
        lst_lst[index].append(i)
        if (idx+1)!=len(xz_array):
            if int(xz_array[idx+1][0]) == 0:
                index+=1
        
    else:
        index+=1
        lst_lst[index].append(i)

(3.214096e-14, -4.041212e-14, 0)
(0.003879738, 0.8085136, 1)
(0.007192398, 1.630418, 2)
(0.02045472, 2.389887, 3)
(0.02958663, 3.173915, 4)
(0.03335121, 3.898587, 5)
(0.03816708, 4.630767, 6)
(0.05059318, 5.321596, 7)
(0.05170819, 5.969282, 8)
(0.06247458, 6.584575, 9)
(0.07747077, 7.17943, 10)
(0.09159598, 7.763325, 11)
(0.07806213, 8.294502, 12)
(0.05269462, 8.771047, 13)
(0.04539942, 9.219163, 14)
(0.03629999, 9.647129, 15)
(0.04725479, 10.0472, 16)
(0.04201541, 10.4353, 17)
(0.03769119, 10.75569, 18)
(0.0317648, 11.04825, 19)
(0.05072266, 11.32402, 20)
(0.07039616, 11.57202, 21)
(0.095297, 11.79524, 22)
(0.09028128, 11.89602, 23)
(0.09669037, 12.008, 24)
(0.1064885, 12.10436, 25)
(0.112343, 12.19147, 26)
(0.1244047, 12.28097, 27)
(0.1056002, 12.29323, 28)
(0.1073966, 12.33543, 29)
(0.1060557, 12.36696, 30)
(0.1205438, 12.42383, 31)
(0.1175632, 12.44527, 32)
(0.1252757, 12.48072, 33)
(0.1270332, 12.5006, 34)
(0.1425398, 12.54514, 35)
(0.1569458, 12.59012, 36)
(0.1601825, 12.6296, 37

(387.6298, 389.9114, 2912)
(388.6677, 389.8064, 2913)
(389.7097, 389.7018, 2914)
(390.7557, 389.5946, 2915)
(391.801, 389.4955, 2916)
(392.8502, 389.3973, 2917)
(393.8996, 389.2965, 2918)
(394.9485, 389.2009, 2919)
(395.9949, 389.0961, 2920)
(397.0358, 388.9826, 2921)
(398.0706, 388.8652, 2922)
(399.1011, 388.7417, 2923)
(400.1264, 388.6147, 2924)
(401.1483, 388.4819, 2925)
(402.1467, 388.3435, 2926)
(403.1207, 388.2065, 2927)
(404.0658, 388.0589, 2928)
(404.9734, 387.8976, 2929)
(405.8576, 387.7328, 2930)
(406.6917, 387.5304, 2931)
(407.5038, 387.3265, 2932)
(408.2533, 387.0592, 2933)
(409.0, 386.8063, 2934)
(409.7127, 386.5377, 2935)
(410.3338, 386.1955, 2936)
(410.9629, 385.896, 2937)
(411.4991, 385.5181, 2938)
(412.0722, 385.1987, 2939)
(412.5625, 384.7855, 2940)
(413.0929, 384.4266, 2941)
(413.5967, 384.0402, 2942)
(413.9967, 383.5453, 2943)
(414.4444, 383.1167, 2944)
(414.7911, 382.58, 2945)
(415.1809, 382.1059, 2946)
(415.4794, 381.537, 2947)
(415.813, 381.036, 2948)
(416.1234, 